id: full-suite
repeats: 3
configs:
  # Data configs
  - model: meta-llama/Llama-3.1-8B-Instruct
    llm_server_type: vllm
    llm_server_config:
      - docker_tag: v0.8.0
      - docker_tag: v0.7.3
    gpu: H100
    region: us-chicago-1
    data:
      - prompt_tokens=32,generated_tokens=1024
      - prompt_tokens=128,generated_tokens=4096
      - prompt_tokens=1024,generated_tokens=32
      - prompt_tokens=4096,generated_tokens=128
      - prompt_tokens=512,generated_tokens=512
      - prompt_tokens=4096,generated_tokens=4096
  - model: meta-llama/Llama-3.1-8B-Instruct
    llm_server_type: vllm
    gpu: A100-80GB
    region: us-east4
    data:
      - prompt_tokens=32,generated_tokens=1024
      - prompt_tokens=128,generated_tokens=4096
      - prompt_tokens=1024,generated_tokens=32
      - prompt_tokens=4096,generated_tokens=128
      - prompt_tokens=512,generated_tokens=512
      - prompt_tokens=4096,generated_tokens=4096

  # vLLM extra args
  - model: meta-llama/Llama-3.1-8B-Instruct
    llm_server_type: vllm
    llm_server_config:
      - docker_tag: v0.7.3
        extra_args: ["--enforce-eager"]
      - docker_tag: v0.7.3
        extra_args: ["--enable-chunked-prefill"]
      - docker_tag: v0.7.3
        extra_args: ["--enforce-eager", "--enable-chunked-prefill"]
    gpu: H100
    region: us-chicago-1
    data:
      - prompt_tokens=128,generated_tokens=4096
      - prompt_tokens=4096,generated_tokens=128

  # More GPUs
  - model:
      - meta-llama/Llama-3.1-8B-Instruct
      # - meta-llama/Llama-3.1-70B-Instruct
    llm_server_type: vllm
    llm_server_config:
      docker_tag: v0.7.3
      extra_args: ["--tensor-parallel-size", "2", "--max-model-len", "8192"]
    gpu: H100:2
    region: us-chicago-1
    data:
      - prompt_tokens=4096,generated_tokens=128
      - prompt_tokens=128,generated_tokens=4096
      - prompt_tokens=2048,generated_tokens=2048

  # - model:
  #     - meta-llama/Llama-3.1-8B-Instruct
  #     - meta-llama/Llama-3.1-70B-Instruct
  #   gpu: H100:4
  #   region: us-chicago-1
  #   data:
  #     - prompt_tokens=4096,generated_tokens=128
  #     - prompt_tokens=128,generated_tokens=4096
  #     - prompt_tokens=4096,generated_tokens=4096
  #   vllm_extra_args:
  #     - ["--tensor-parallel-size", "4", "--max-model-len", "8192"]
