id: region-test
repeats: 3
configs:
  - model: meta-llama/Llama-3.1-8B-Instruct
    llm_server_type: vllm
    gpu: H100
    data: prompt_tokens=512,generated_tokens=128
    region:
      - us-ashburn-1
      - us-chicago-1
      - us-east-1
      - us-east4
