id: tensorrt-llm
repeats: 3
base_config:
  region: us-chicago-1
  llm_server_type: trtllm
  data:
    - prompt_tokens=256,generated_tokens=4096
    - prompt_tokens=4096,generated_tokens=256
    - prompt_tokens=2048,generated_tokens=2048
configs:
  - model: Qwen/Qwen2.5-Coder-7B-Instruct
    gpu: H100
