id: trtllm-engine
configs:
  - model: meta-llama/Llama-3.1-8B-Instruct
    region: us-ashburn-1
    llm_engine_type: trtllm
    llm_engine_version: 0.17.0.post1
    gpu: H100
    data: prompt_tokens=512,generated_tokens=128
recompute: true
